import { defineStrings } from '@/ui/i18n/core';
import type { NumberFormatter } from '@/ui/i18n/locale';

/** Strings of the popup shell: header, banners, the download list, the footer, inline errors, the item editor. */
export const popupStrings = defineStrings({
  ko: {
    // header
    historyButton: '기록',
    settingsButton: '설정',
    noAccountName: '계정을 확인하지 못했어요',
    noAccountHint: '디스코드에 로그인하면 여기에 표시돼요',
    lastAccountTitle: '마지막으로 확인한 계정이에요',

    // banners
    bannerNoDiscord: '열려 있는 디스코드 탭이 없어요. 디스코드를 열고 로그인해 주세요.',
    openDiscord: '디스코드 열기',
    bannerChecking: '계정 확인 중…',
    bannerCheckingHint: '디스코드 탭에서 로그인한 계정을 확인하고 있어요.',
    bannerExpired: '디스코드 로그인 정보가 만료됐어요. 디스코드 탭을 새로고침한 뒤 다시 시도해 주세요.',
    bannerInject: '디스코드 화면에 버튼을 붙이지 못했어요. 디스코드가 업데이트되어 화면 구조가 바뀐 것 같아요.',
    bannerInjectReason: (reason: string) => `(${reason})`,
    bannerConnection: '확장 프로그램의 백그라운드와 연결하지 못했어요. 팝업을 닫고 다시 열어 보세요.',

    // toggle
    showButtons: '디스코드에 버튼 표시',
    showButtonsHint: '채널과 DM 행에 ⤓ 버튼을 보여 줘요.',

    // list
    queueLabel: '다운로드 목록',
    emptyHint: '디스코드에서 채널이나 DM에 마우스를 올리고 ⤓ 버튼을 누르세요',
    commonBadge: '공통 설정',
    ownBadge: '개별 설정',
    guildBadge: '서버 설정',
    categoryBadge: '카테고리 설정',
    commonBadgeTitle: '공통 설정을 따라가요. 공통 설정을 바꾸면 같이 바뀌어요.',
    guildBadgeTitle: '서버 설정을 따라가요. 서버 설정을 바꾸면 같이 바뀌어요.',
    categoryBadgeTitle: '카테고리 설정을 따라가요. 카테고리 설정을 바꾸면 같이 바뀌어요.',
    ownBadgeTitle: '이 채팅만의 설정을 써요.',
    startItem: (label: string) => `${label} 다운로드`,
    editItem: (label: string) => `${label} 설정`,
    removeItem: (label: string) => `${label} 목록에서 빼기`,
    startBusyTitle: '다운로드가 진행 중이에요',
    retry: '재시도',
    retryItem: (label: string) => `${label} 다시 시도`,

    // the tree: server and category lines (docs/PLAN.md §7.2a)
    unknownServer: '서버',
    unknownCategory: '카테고리',
    groupCount: (count: number, fmt: NumberFormatter) => `${fmt(count)}개`,
    groupCountAll: (count: number, fmt: NumberFormatter) => `전체 ${fmt(count)}개`,
    groupCountTitle: (count: number, fmt: NumberFormatter) => `목록에 담긴 채널 ${fmt(count)}개`,
    groupCountAllTitle: (count: number, fmt: NumberFormatter) => `볼 수 있는 채널을 모두 담았어요 (${fmt(count)}개)`,
    overrideChip: (count: number, fmt: NumberFormatter) => `개별 ${fmt(count)}`,
    overrideChipTitle: (count: number, fmt: NumberFormatter) => `따로 설정한 채널이 ${fmt(count)}개 있어요`,
    failedChip: (count: number, fmt: NumberFormatter) => `미완료 ${fmt(count)}`,
    failedChipTitle: (count: number, fmt: NumberFormatter) => `끝까지 받지 못한 채널이 ${fmt(count)}개 있어요. 펼쳐서 다시 시도할 수 있어요`,
    subtitleMore: '…',
    startGroup: (name: string) => `${name} 채널 다운로드`,
    editGroup: (name: string) => `${name} 설정`,
    removeGroup: (name: string) => `${name} 채널 목록에서 빼기`,
    removeGroupConfirm: (count: number, fmt: NumberFormatter) => `채널 ${fmt(count)}개를 목록에서 뺄까요?`,
    removeGroupYes: '빼기',
    removeGroupNo: '취소',
    groupProgressLabel: (name: string) => `${name} 진행률`,
    groupProgressText: (finished: number, total: number, fmt: NumberFormatter) => `${fmt(finished)}/${fmt(total)}`,

    // progress
    phaseResolving: '채팅 정보 확인 중',
    phaseMessages: '메시지 가져오는 중',
    phaseThreads: '스레드 찾는 중',
    phaseAttachments: '첨부파일 받는 중',
    phaseWriting: '파일 만드는 중',
    phaseSaving: '저장하는 중',
    statusWaiting: '대기 중',
    statusRunning: '진행 중',
    statusPaused: '잠시 멈춤',
    statusDone: '완료',
    statusPartial: '일부만 저장됨',
    statusFailed: '실패',
    statusCancelled: '취소됨',
    progressCount: (fetched: number, expected: number | null, fmt: NumberFormatter) =>
      expected === null ? `${fmt(fetched)}개` : `${fmt(fetched)} / ${fmt(expected)}개`,
    itemProgress: (label: string) => `${label} 진행률`,

    // failures
    failurePartial: '일부만 저장했어요.',
    failureFailed: '다운로드하지 못했어요.',
    failureCancelled: '취소했어요.',
    errorAuth: '디스코드 로그인 정보가 만료됐어요. 디스코드 탭을 새로고침해 주세요.',
    errorForbidden: '이 채팅을 볼 권한이 없어요.',
    errorNotFound: '채팅을 찾을 수 없어요. 삭제됐을 수 있어요.',
    errorRateLimited: '디스코드가 요청을 제한했어요. 잠시 뒤에 다시 시도해 주세요.',
    errorBlocked: '디스코드가 요청을 막았어요. 잠시 뒤에 다시 시도해 주세요.',
    errorNetwork: '네트워크에 연결하지 못했어요.',
    errorServer: '디스코드 서버에 문제가 있어요.',
    errorCancelled: '취소했어요.',
    errorInterrupted: '중간에 끊겼어요. 다시 시도해 주세요.',
    errorUnknown: '알 수 없는 오류가 났어요.',

    // footer
    downloadAll: '전체 다운로드',
    openCommonSettings: '공통 설정 열기',
    emptyDownloadTitle: '다운로드 목록이 비어 있어요',
    clearList: '목록 비우기',
    clearConfirm: '목록을 모두 비울까요?',
    clearConfirmYes: '비우기',
    clearConfirmNo: '취소',
    overallProgress: '전체 진행률',
    overallText: (finished: number, total: number, percent: number, fmt: NumberFormatter) => `${fmt(finished)}/${fmt(total)} · ${fmt(percent)}%`,
    pausedRateLimit: '디스코드 요청 제한 때문에 잠시 쉬고 있어요. 곧 이어서 받아요.',
    cancel: '취소',
    cancelling: '취소하는 중…',

    // the safety question before a big download (Discord can limit an account that makes a lot of automated requests)
    riskMessage: (count: number, fmt: NumberFormatter) => `채팅 ${fmt(count)}개를 한 번에 받으려고 해요. 대량 다운로드는 디스코드 계정이 제한될 위험이 커져요.`,
    riskManyChats: (max: number, fmt: NumberFormatter) => `채팅이 많아요 (${fmt(max)}개 초과)`,
    riskUnbounded: '기간·개수 제한 없이 전체 메시지를 받는 채팅이 있어요',
    riskManyMessages: (estimate: number, fmt: NumberFormatter) => `요청하는 메시지가 매우 많아요 (약 ${fmt(estimate)}개)`,
    riskThreads: '스레드 포함은 요청이 크게 늘어요',
    riskContinue: '계속 받기',
    riskCancel: '취소',

    // a job that ended while the popup was open
    finishedDone: '다운로드를 마쳤어요',
    finishedWithProblems: (done: number, problems: number, fmt: NumberFormatter) => `${fmt(done)}개 완료, ${fmt(problems)}개는 끝내지 못했어요`,
    finishedCancelled: '다운로드를 취소했어요',
    finishedFailed: '다운로드하지 못했어요',
    openFolder: '폴더 열기',

    // inline errors of the background worker (docs/PLAN.md §5.3)
    errNoAccount: '디스코드 계정을 아직 확인하지 못했어요. 디스코드 탭에서 로그인한 뒤 다시 시도해 주세요.',
    errNoConsent: '먼저 안내를 읽고 동의해 주세요.',
    errBusy: '이미 다운로드가 진행 중이에요. 끝난 뒤에 다시 시도해 주세요.',
    errEmpty: '다운로드할 채팅이 없어요.',
    errInvalid: '요청이 올바르지 않아요.',
    errForbiddenPath: '이 위치에는 저장할 수 없어요. 폴더 이름을 확인해 주세요.',
    errHttp: '디스코드와 통신하지 못했어요.',
    errUnknown: '문제가 생겼어요. 다시 시도해 주세요.',
    errConnection: '확장 프로그램과 연결하지 못했어요. 팝업을 닫고 다시 열어 보세요.',
    errDetail: (detail: string) => `(${detail})`,

    // sub views
    commonSettingsTitle: '공통 설정',
    commonSettingsNote: '바뀐 내용은 바로 저장돼요. 따로 설정하지 않은 채팅은 모두 이 설정을 따라가요.',
    editTitle: '채팅 설정',
    parentCommon: '공통 설정',
    parentGuild: '서버 설정',
    parentCategory: '카테고리 설정',
    editFollows: (parent: string) => `지금은 ${parent}을 따라가요. 여기서 저장하면 이 채팅만 다른 설정을 써요.`,
    editHasOwn: (parent: string) => `이 채팅만의 설정을 쓰고 있어요. ${parent}을 바꿔도 이 채팅은 그대로예요.`,
    editParentNow: (parent: string, summary: string) => `${parent}: ${summary}`,
    editRevert: '공통 설정으로 되돌리기',
    editRevertGuild: '서버 설정으로 되돌리기',
    editRevertCategory: '카테고리 설정으로 되돌리기',
    editMissing: '이 채팅은 더 이상 목록에 없어요.',
    editInvalid: '올바르지 않은 값이 있어요',
    guildSettingsTitle: (name: string) => `서버 설정 · ${name}`,
    categorySettingsTitle: (name: string) => `카테고리 설정 · ${name}`,
    groupAppliesTo: (count: number, fmt: NumberFormatter) => `채널 ${fmt(count)}개에 적용돼요`,
    groupOverridesNotice: (count: number, fmt: NumberFormatter) => `아래 개별 설정 ${fmt(count)}개가 이 설정으로 바뀌어요`,
    groupNoteNew: '저장하면 지금 담겨 있는 채널과 앞으로 담는 채널이 모두 이 설정을 따라가요.',
    groupNoteOwn: '따로 정한 설정을 쓰고 있어요. 저장하면 아래 채널 전부에 한 번에 적용돼요.',
    groupRevert: '상위 설정으로 되돌리기',
    groupRevertTitle: '이 줄에 따로 정한 설정만 지워요. 채널의 개별 설정은 그대로예요.',
    groupMissing: '여기에 담긴 채널이 더 이상 목록에 없어요.',
    loading: '불러오는 중…',
  },
  en: {
    historyButton: 'History',
    settingsButton: 'Settings',
    noAccountName: 'Account not found yet',
    noAccountHint: 'Shown here once you are logged in to Discord',
    lastAccountTitle: 'The last account that was seen',

    bannerNoDiscord: 'No Discord tab is open. Open Discord and log in.',
    openDiscord: 'Open Discord',
    bannerChecking: 'Checking the account…',
    bannerCheckingHint: 'Looking up the account that is logged in on the Discord tab.',
    bannerExpired: 'Your Discord login has expired. Reload the Discord tab and try again.',
    bannerInject: 'The buttons could not be added to the Discord page. Discord has probably been updated and its layout changed.',
    bannerInjectReason: (reason) => `(${reason})`,
    bannerConnection: 'Could not reach the extension background. Close this popup and open it again.',

    showButtons: 'Show buttons on Discord',
    showButtonsHint: 'Puts a ⤓ button on channel and DM rows.',

    queueLabel: 'Download list',
    emptyHint: 'On Discord, hover a channel or DM and press the ⤓ button',
    commonBadge: 'Common settings',
    ownBadge: 'Own settings',
    guildBadge: 'Server settings',
    categoryBadge: 'Category settings',
    commonBadgeTitle: 'Follows the common settings, and changes with them.',
    guildBadgeTitle: 'Follows the server settings, and changes with them.',
    categoryBadgeTitle: 'Follows the category settings, and changes with them.',
    ownBadgeTitle: 'This chat has settings of its own.',
    startItem: (label) => `Download ${label}`,
    editItem: (label) => `Settings of ${label}`,
    removeItem: (label) => `Remove ${label} from the list`,
    startBusyTitle: 'A download is in progress',
    retry: 'Retry',
    retryItem: (label) => `Retry ${label}`,

    unknownServer: 'Server',
    unknownCategory: 'Category',
    groupCount: (count, fmt) => `${fmt(count)} ${count === 1 ? 'chat' : 'chats'}`,
    groupCountAll: (count, fmt) => `All ${fmt(count)}`,
    groupCountTitle: (count, fmt) => `${fmt(count)} ${count === 1 ? 'chat' : 'chats'} in the list`,
    groupCountAllTitle: (count, fmt) => `Every channel you can see is in the list (${fmt(count)})`,
    overrideChip: (count, fmt) => `${fmt(count)} own`,
    overrideChipTitle: (count, fmt) => `${fmt(count)} ${count === 1 ? 'chat has' : 'chats have'} settings of their own`,
    failedChip: (count, fmt) => `${fmt(count)} unfinished`,
    failedChipTitle: (count, fmt) => `${fmt(count)} ${count === 1 ? 'chat' : 'chats'} did not finish. Open the group to retry`,
    subtitleMore: '…',
    startGroup: (name) => `Download the chats of ${name}`,
    editGroup: (name) => `Settings of ${name}`,
    removeGroup: (name) => `Remove the chats of ${name} from the list`,
    removeGroupConfirm: (count, fmt) => `Remove ${fmt(count)} ${count === 1 ? 'chat' : 'chats'} from the list?`,
    removeGroupYes: 'Remove',
    removeGroupNo: 'Cancel',
    groupProgressLabel: (name) => `Progress of ${name}`,
    groupProgressText: (finished, total, fmt) => `${fmt(finished)}/${fmt(total)}`,

    phaseResolving: 'Looking up the chat',
    phaseMessages: 'Fetching messages',
    phaseThreads: 'Finding threads',
    phaseAttachments: 'Saving attachments',
    phaseWriting: 'Writing the file',
    phaseSaving: 'Saving',
    statusWaiting: 'Waiting',
    statusRunning: 'Running',
    statusPaused: 'Paused',
    statusDone: 'Done',
    statusPartial: 'Partly saved',
    statusFailed: 'Failed',
    statusCancelled: 'Cancelled',
    progressCount: (fetched, expected, fmt) =>
      expected === null ? `${fmt(fetched)} ${fetched === 1 ? 'message' : 'messages'}` : `${fmt(fetched)} / ${fmt(expected)}`,
    itemProgress: (label) => `Progress of ${label}`,

    failurePartial: 'Only part of it was saved.',
    failureFailed: 'It could not be downloaded.',
    failureCancelled: 'Cancelled.',
    errorAuth: 'Your Discord login has expired. Reload the Discord tab.',
    errorForbidden: 'You do not have access to this chat.',
    errorNotFound: 'The chat was not found. It may have been deleted.',
    errorRateLimited: 'Discord rate-limited the requests. Try again in a moment.',
    errorBlocked: 'Discord blocked the requests. Try again in a moment.',
    errorNetwork: 'Could not reach the network.',
    errorServer: 'Discord had a problem on its side.',
    errorCancelled: 'Cancelled.',
    errorInterrupted: 'It was interrupted. Try again.',
    errorUnknown: 'Something went wrong.',

    downloadAll: 'Download all',
    openCommonSettings: 'Open the common settings',
    emptyDownloadTitle: 'The download list is empty',
    clearList: 'Clear list',
    clearConfirm: 'Clear the whole list?',
    clearConfirmYes: 'Clear',
    clearConfirmNo: 'Cancel',
    overallProgress: 'Overall progress',
    overallText: (finished, total, percent, fmt) => `${fmt(finished)}/${fmt(total)} · ${fmt(percent)}%`,
    pausedRateLimit: 'Pausing for a moment because of Discord rate limits. It continues by itself.',
    cancel: 'Cancel',
    cancelling: 'Cancelling…',

    riskMessage: (count, fmt) => `You are about to download ${fmt(count)} ${count === 1 ? 'chat' : 'chats'} at once. Large downloads make it much more likely that Discord limits your account.`,
    riskManyChats: (max, fmt) => `Many chats (more than ${fmt(max)})`,
    riskUnbounded: 'Some chats download every message, with no period or count limit',
    riskManyMessages: (estimate, fmt) => `A very large number of messages is requested (about ${fmt(estimate)})`,
    riskThreads: 'Including threads multiplies the number of requests',
    riskContinue: 'Download anyway',
    riskCancel: 'Cancel',

    finishedDone: 'The download is finished',
    finishedWithProblems: (done, problems, fmt) => `${fmt(done)} done, ${fmt(problems)} not finished`,
    finishedCancelled: 'The download was cancelled',
    finishedFailed: 'The download failed',
    openFolder: 'Open folder',

    errNoAccount: 'The Discord account is not known yet. Log in on a Discord tab and try again.',
    errNoConsent: 'Read the notice and agree to it first.',
    errBusy: 'A download is already running. Try again when it is finished.',
    errEmpty: 'There is no chat to download.',
    errInvalid: 'The request is not valid.',
    errForbiddenPath: 'Files cannot be saved there. Check the folder name.',
    errHttp: 'Could not talk to Discord.',
    errUnknown: 'Something went wrong. Please try again.',
    errConnection: 'Could not reach the extension. Close this popup and open it again.',
    errDetail: (detail) => `(${detail})`,

    commonSettingsTitle: 'Common settings',
    commonSettingsNote: 'Changes are saved right away. Every chat without settings of its own follows these.',
    editTitle: 'Chat settings',
    parentCommon: 'common settings',
    parentGuild: 'server settings',
    parentCategory: 'category settings',
    editFollows: (parent) => `This chat follows the ${parent}. Saving here gives it settings of its own.`,
    editHasOwn: (parent) => `This chat has settings of its own. Changing the ${parent} does not affect it.`,
    editParentNow: (parent, summary) => `${parent.charAt(0).toUpperCase()}${parent.slice(1)}: ${summary}`,
    editRevert: 'Reset to common settings',
    editRevertGuild: 'Reset to server settings',
    editRevertCategory: 'Reset to category settings',
    editMissing: 'This chat is no longer in the list.',
    editInvalid: 'Some values are not valid',
    guildSettingsTitle: (name) => `Server settings · ${name}`,
    categorySettingsTitle: (name) => `Category settings · ${name}`,
    groupAppliesTo: (count, fmt) => `Applies to ${fmt(count)} ${count === 1 ? 'chat' : 'chats'}`,
    groupOverridesNotice: (count, fmt) => `${fmt(count)} ${count === 1 ? 'setting' : 'settings'} of chats below will be replaced by these`,
    groupNoteNew: 'Once saved, the chats in the list now and the ones you add later all follow these settings.',
    groupNoteOwn: 'These settings were set for this line. Saving applies them to every chat below at once.',
    groupRevert: 'Reset to the settings above',
    groupRevertTitle: 'Only removes the settings set for this line. Chats keep their own settings.',
    groupMissing: 'The chats here are no longer in the list.',
    loading: 'Loading…',
  },
});

/** The first-run notice (docs/PLAN.md §2 #11) and its "read it again" screen. */
export const consentStrings = defineStrings({
  ko: {
    title: '시작하기 전에 꼭 읽어 주세요',
    intro: '이 확장 프로그램은 내 디스코드 계정으로 볼 수 있는 대화를 파일로 저장해요. 사용하기 전에 아래 내용을 확인해 주세요.',
    tosTitle: '디스코드 이용약관과 계정 위험',
    tosBody:
      '디스코드 이용약관은 사용자 계정을 자동화된 방식으로 쓰는 것을 허용하지 않아요. 이 확장 프로그램을 쓰면 계정이 경고를 받거나 제한·정지될 수 있어요. 이 위험은 사용자 본인이 감수해야 해요.',
    ownTitle: '내 대화의 개인 백업용으로만 쓰세요',
    ownBody: '본인 계정의 대화를 개인 기록으로 보관하는 용도로만 쓰세요. 다른 사람의 대화나 개인정보를 허락 없이 공개하거나 퍼뜨리지 마세요.',
    tokenTitle: '로그인 토큰을 읽어요',
    tokenBody:
      '동의하면 디스코드 웹 페이지가 보내는 요청에서 로그인 토큰(Authorization 값)을 읽어 이 브라우저의 메모리에만 두고, 내 계정으로 채팅을 불러올 때 discord.com에만 보내요. 파일·기록에는 남기지 않고, 크롬을 끄면 사라져요.',
    localTitle: '채팅은 이 컴퓨터에 파일로 저장돼요',
    localBody: '가져온 대화는 이 브라우저에서 파일로 바로 저장돼요. 별도 서버로 보내거나 분석 도구를 쓰지 않아요.',
    rateTitle: '천천히, 조금씩 받아요',
    rateBody: '디스코드에 부담을 주지 않도록 요청 사이에 간격을 두어요. 메시지가 많으면 시간이 오래 걸리고, 요청이 많을수록 위험도 커져요.',
    accept: '동의하고 시작',
    acceptNote: '동의하기 전에는 아무것도 읽거나 다운로드하지 않아요.',
    reviewTitle: '약관·위험 안내',
    consentedAt: (time: string) => `${time}에 동의했어요.`,
    close: '닫기',
  },
  en: {
    title: 'Please read this before you start',
    intro: 'This extension saves the conversations your Discord account can see as files. Check the points below before you use it.',
    tosTitle: 'Discord Terms of Service and account risk',
    tosBody:
      'Discord’s Terms of Service do not allow using a user account in an automated way. Using this extension can get your account warned, limited or banned. You accept that risk yourself.',
    ownTitle: 'Only for personal backups of your own chats',
    ownBody: 'Use it only to keep a personal record of the conversations of your own account. Do not publish or spread other people’s messages or personal data without their permission.',
    tokenTitle: 'It reads your login token',
    tokenBody:
      'Once you agree, it reads the login token (the Authorization value) from requests the Discord web page sends, keeps it in this browser’s memory only, and sends it only to discord.com when loading chats with your account. It is not written to files or the history and disappears when Chrome is closed.',
    localTitle: 'Chats are saved as files on this computer',
    localBody: 'The chats are saved as files right in this browser. Nothing is sent to a server of ours, and there are no analytics.',
    rateTitle: 'It downloads slowly, a little at a time',
    rateBody: 'Requests are spaced out so Discord is not burdened. A long chat takes a long time, and the more requests are made, the higher the risk.',
    accept: 'Agree and start',
    acceptNote: 'Until you agree, nothing is read or downloaded.',
    reviewTitle: 'Terms and risk notice',
    consentedAt: (time) => `You agreed on ${time}.`,
    close: 'Close',
  },
});

/** The app settings screen (the gear in the header). */
export const appSettingsStrings = defineStrings({
  ko: {
    title: '설정',
    sectionFiles: '파일 저장',
    folderLabel: '폴더 이름',
    folderHelp: '다운로드 폴더 안에 이 이름의 폴더를 만들어 저장해요.',
    folderEmpty: '폴더 이름을 입력하세요.',
    folderTooLong: (max: number, fmt: NumberFormatter) => `폴더 이름은 ${fmt(max)}자 이하로 해 주세요.`,
    folderInvalid: '폴더 이름에는 \\ / : * ? " < > | 문자를 쓸 수 없어요.',
    dateInFileName: '파일 이름에 날짜 넣기',
    dateInFileNameHelp: '예: 서버 - 채널 (2026-10-06).html',
    timeZoneLabel: '시간대',
    timeZoneHelp: '파일 이름의 날짜와 내보낸 파일 안의 시각에 쓰여요.',
    timeZoneAuto: (zone: string) => (zone === '' ? '자동 (브라우저 시간대)' : `자동 (${zone})`),
    sectionNotify: '알림',
    notifyOnComplete: '다운로드가 끝나면 알림 받기',
    sectionShortcut: '단축키',
    shortcutLabel: '보고 있는 채팅 담기·빼기',
    shortcutNone: '설정 안 됨',
    shortcutChange: '변경',
    shortcutHelp: '크롬의 단축키 설정 화면이 새 탭으로 열려요.',
    sectionNotice: '안내',
    showConsent: '약관·위험 안내 다시 보기',
  },
  en: {
    title: 'Settings',
    sectionFiles: 'Saving files',
    folderLabel: 'Folder name',
    folderHelp: 'Files are saved in a folder with this name inside your download folder.',
    folderEmpty: 'Enter a folder name.',
    folderTooLong: (max, fmt) => `Keep the folder name to ${fmt(max)} characters or fewer.`,
    folderInvalid: 'A folder name cannot contain \\ / : * ? " < > |',
    dateInFileName: 'Put the date in file names',
    dateInFileNameHelp: 'Example: Server - Channel (2026-10-06).html',
    timeZoneLabel: 'Time zone',
    timeZoneHelp: 'Used for the date in file names and the times inside exported files.',
    timeZoneAuto: (zone) => (zone === '' ? 'Auto (browser time zone)' : `Auto (${zone})`),
    sectionNotify: 'Notifications',
    notifyOnComplete: 'Notify me when a download is done',
    sectionShortcut: 'Keyboard shortcut',
    shortcutLabel: 'Add / remove the chat you are viewing',
    shortcutNone: 'Not set',
    shortcutChange: 'Change',
    shortcutHelp: 'Opens the shortcut settings page of Chrome in a new tab.',
    sectionNotice: 'Notice',
    showConsent: 'Read the terms and risk notice again',
  },
});

/** The download history screen (docs/PLAN.md §2 #16). */
export const historyStrings = defineStrings({
  ko: {
    title: '다운로드 기록',
    empty: '아직 받은 기록이 없어요.',
    statusDone: '완료',
    statusPartial: '일부 저장',
    statusFailed: '실패',
    messages: (count: number, fmt: NumberFormatter) => `메시지 ${fmt(count)}개`,
    openFolder: '폴더 열기',
    openFolderFor: (label: string) => `${label} 폴더 열기`,
    rerun: '다시 받기',
    rerunFor: (label: string) => `${label} 다시 받기`,
    clear: '기록 지우기',
    clearConfirm: '기록을 모두 지울까요?',
    clearConfirmYes: '지우기',
    clearConfirmNo: '취소',
    listLabel: '다운로드 기록 목록',
  },
  en: {
    title: 'Download history',
    empty: 'Nothing has been downloaded yet.',
    statusDone: 'Done',
    statusPartial: 'Partly saved',
    statusFailed: 'Failed',
    messages: (count, fmt) => `${fmt(count)} ${count === 1 ? 'message' : 'messages'}`,
    openFolder: 'Open folder',
    openFolderFor: (label) => `Open the folder of ${label}`,
    rerun: 'Download again',
    rerunFor: (label) => `Download ${label} again`,
    clear: 'Clear history',
    clearConfirm: 'Clear the whole history?',
    clearConfirmYes: 'Clear',
    clearConfirmNo: 'Cancel',
    listLabel: 'Download history list',
  },
});
